/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getHealthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getReadyz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/slides": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listSlides"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/slides/{slide_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSlide"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/slides/{slide_id}/dzi": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSlideDzi"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/slides/{slide_id}_files/{level}/{column}_{row}.jpeg": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSlideTile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/slides/{slide_id}/thumbnail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSlideThumbnail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/slides/{slide_id}/segment": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["segmentSlideRegion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponse: {
      status: string;
    };
    ReadyResponse: {
      status: string;
      slides: number;
    };
    Dimensions: {
      width: number;
      height: number;
    };
    SlideMetadata: {
      id: string;
      name: string;
      filename: string;
      format: string;
      dimensions: components["schemas"]["Dimensions"];
      level_count: number;
      level_dimensions: components["schemas"]["Dimensions"][];
      tile_size: number;
      mpp_x?: number | null;
      mpp_y?: number | null;
      objective_power?: number | null;
      properties: {
        [key: string]: string;
      };
    };
    SlideListResponse: {
      slides: components["schemas"]["SlideMetadata"][];
    };
    SegmentRequest: {
      x: number;
      y: number;
      width: number;
      height: number;
      /** @default 2500 */
      max_nuclei: number;
    };
    Region: {
      x: number;
      y: number;
      width: number;
      height: number;
    };
    Nucleus: {
      id: number;
      centroid: number[];
      area: number;
      bbox: number[];
      confidence?: number | null;
      polygon: number[][];
    };
    SegmentResponse: {
      slide_id: string;
      method: string;
      region: components["schemas"]["Region"];
      count: number;
      elapsed_ms: number;
      nuclei: components["schemas"]["Nucleus"][];
    };
    ErrorResponse: {
      error: {
        code: string;
        message: string;
        details?: {
          [key: string]: unknown;
        };
      };
    };
  };
  responses: {
    /** @description JSON API error. */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    SlideId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Health status. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  getReadyz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Readiness status. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  listSlides: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Available slides. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SlideListResponse"];
        };
      };
    };
  };
  getSlide: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slide_id: components["parameters"]["SlideId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Slide metadata. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SlideMetadata"];
        };
      };
      404: components["responses"]["Error"];
    };
  };
  getSlideDzi: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slide_id: components["parameters"]["SlideId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deep Zoom XML descriptor. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": string;
        };
      };
    };
  };
  getSlideTile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slide_id: components["parameters"]["SlideId"];
        level: number;
        column: number;
        row: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JPEG tile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "image/jpeg": string;
        };
      };
    };
  };
  getSlideThumbnail: {
    parameters: {
      query?: {
        size?: number;
      };
      header?: never;
      path: {
        slide_id: components["parameters"]["SlideId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JPEG thumbnail. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "image/jpeg": string;
        };
      };
    };
  };
  segmentSlideRegion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slide_id: components["parameters"]["SlideId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SegmentRequest"];
      };
    };
    responses: {
      /** @description Nuclei segmentation. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SegmentResponse"];
        };
      };
      413: components["responses"]["Error"];
    };
  };
}
